root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  full_bin = "cd /app && ./backend/tmp/server"
  cmd = "go build -o ./tmp/server ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "internal/api/gen", "bin"]
  exclude_regex = ["_test\\.go$"]
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "tpl", "tmpl"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
